# Generated by Django 6.0.4 on 2026-04-21 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enterprise", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "cycle_type",
                    models.CharField(
                        choices=[("crop", "Crop"), ("livestock", "Livestock")],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("expected_duration", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("crop_type", models.CharField(blank=True, max_length=100)),
                ("season", models.CharField(blank=True, max_length=100)),
                ("livestock_type", models.CharField(blank=True, max_length=100)),
                ("breed", models.CharField(blank=True, max_length=100)),
                ("initial_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycles",
                        to="enterprise.enterprise",
                    ),
                ),
            ],
        ),
    ]
