# Generated by Django 6.0.4 on 2026-06-11 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FEED', 'Feeding'), ('VACCINE', 'Vaccination'), ('CLEANING', 'Cleaning'), ('OTHERS', 'Others')], default='VACCINE', max_length=12)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=6)),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('overdue', 'Overdue'), ('pending', 'Pending'), ('Completed', 'Completed')], default='pending', max_length=12)),
                ('Cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycles.cycle')),
            ],
        ),
    ]
