# Generated by Django 6.0.4 on 2026-06-27 01:52

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FEED', 'Feeding'), ('VACCINE', 'Vaccination'), ('CLEANING', 'Cleaning'), ('OTHERS', 'Others')], default='VACCINE', max_length=12)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=6)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='no description for this task')),
                ('due_date', models.DateField()),
                ('time', models.TimeField(default=datetime.time(9, 0))),
                ('status', models.CharField(choices=[('overdue', 'Overdue'), ('pending', 'Pending'), ('completed', 'Completed')], db_default='pending', default='pending', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle', to='cycles.cycle')),
            ],
        ),
    ]
