# Generated by Django 6.0.4 on 2026-06-11 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('overdue', 'Overdue'), ('pending', 'Pending'), ('Completed', 'Completed')], db_default='12:00', default='pending', max_length=12),
        ),
    ]
