# Generated by Django 6.0.4 on 2026-06-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='is_complete',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
