# Generated by Django 6.0.4 on 2026-06-14 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
        ('tasks', '0002_task_time_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='no description for this task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle', to='cycles.cycle'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('overdue', 'Overdue'), ('pending', 'Pending'), ('Completed', 'Completed')], db_default='pending', default='pending', max_length=12),
        ),
    ]
