# Generated by Django 6.0.4 on 2026-06-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_created_at_task_description_alter_task_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('overdue', 'Overdue'), ('pending', 'Pending'), ('completed', 'Completed')], db_default='pending', default='pending', max_length=12),
        ),
    ]
