# Generated by Django 6.0.4 on 2026-06-27 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cycles.cycle'),
        ),
    ]
