# Generated by Django 6.0.4 on 2026-06-27 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_initial'),
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.enterprise'),
        ),
    ]
