# Generated by Django 6.0.4 on 2026-04-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="role",
            field=models.CharField(
                choices=[
                    ("farmer", "Farmer"),
                    ("manager", "Manager"),
                    ("admin", "Admin"),
                ],
                default="farmer",
                max_length=20,
            ),
        ),
    ]
