# Generated by Django 6.0.4 on 2026-06-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_farmer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='role',
            field=models.CharField(choices=[('farm manager', 'Farm Manager'), ('farm staff', 'Farm Staff'), ('admin', 'Admin')], default='farm manager', max_length=20),
        ),
    ]
