# Generated by Django 6.0.4 on 2026-04-21 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enterprise", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("asset_type", models.CharField(max_length=100)),
                (
                    "purchase_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("purchase_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enterprise.enterprise",
                    ),
                ),
            ],
        ),
    ]
